### ISSUE TITLE
チケットの書き方のサンプル

### ISSUE THREAD

**Issue by bishantakuma-abewadana** [belion-freee/hello-world-rails#17]
機能追加の時のチケットの書き方のサンプルです。
もちろんこちら以外の書き方でも構いませんが、書き方がよくわからない場合は参考にしてください。

## 概要
ざっくりとした概要を加えます。
なぜこの機能が必要なのかとか書きます。

## 要件
より具体的な要件を記載します。
ER図やクラス設計の解説を加えます。

## TODO
TODOリストをチェックボックスで記載する。
`[ ]` って書くとチェックボックスになります。

こんな感じで書くとチェックボックスを箇条書きにして、ネストもできます。
```
- [ ] migration
  - [ ] sample01
  - [ ] sample02
```

- [ ] migration
  - [ ] sample01
  - [ ] sample02
- [ ] model
  - [ ] sample01 model
  - [ ] sample02 model
  - [ ] sample01 model(test)
  - [ ] sample02 model(test)
- [ ] controller
  - [ ] sample01 controller
  - [ ] sample02 controller
  - [ ] sample01 controller(test)
  - [ ] sample02 controller(test)
- [ ] controller
  - [ ] sample01 view(index)
  - [ ] sample01 view(show)
  - [ ] sample01 view(new)
  - [ ] sample01 view(edit)
  - [ ] sample02 view(index)
  - [ ] sample02 view(show)
  - [ ] sample02 view(new)
  - [ ] sample02 view(edit)
